/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/rook/rook/pkg/apis/chubao.rook.io/v1alpha1"
	scheme "github.com/rook/rook/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ChubaoMonitorsGetter has a method to return a ChubaoMonitorInterface.
// A group's client should implement this interface.
type ChubaoMonitorsGetter interface {
	ChubaoMonitors(namespace string) ChubaoMonitorInterface
}

// ChubaoMonitorInterface has methods to work with ChubaoMonitor resources.
type ChubaoMonitorInterface interface {
	Create(*v1alpha1.ChubaoMonitor) (*v1alpha1.ChubaoMonitor, error)
	Update(*v1alpha1.ChubaoMonitor) (*v1alpha1.ChubaoMonitor, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ChubaoMonitor, error)
	List(opts v1.ListOptions) (*v1alpha1.ChubaoMonitorList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ChubaoMonitor, err error)
	ChubaoMonitorExpansion
}

// chubaoMonitors implements ChubaoMonitorInterface
type chubaoMonitors struct {
	client rest.Interface
	ns     string
}

// newChubaoMonitors returns a ChubaoMonitors
func newChubaoMonitors(c *ChubaoV1alpha1Client, namespace string) *chubaoMonitors {
	return &chubaoMonitors{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the chubaoMonitor, and returns the corresponding chubaoMonitor object, and an error if there is any.
func (c *chubaoMonitors) Get(name string, options v1.GetOptions) (result *v1alpha1.ChubaoMonitor, err error) {
	result = &v1alpha1.ChubaoMonitor{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("chubaomonitors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ChubaoMonitors that match those selectors.
func (c *chubaoMonitors) List(opts v1.ListOptions) (result *v1alpha1.ChubaoMonitorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ChubaoMonitorList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("chubaomonitors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested chubaoMonitors.
func (c *chubaoMonitors) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("chubaomonitors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a chubaoMonitor and creates it.  Returns the server's representation of the chubaoMonitor, and an error, if there is any.
func (c *chubaoMonitors) Create(chubaoMonitor *v1alpha1.ChubaoMonitor) (result *v1alpha1.ChubaoMonitor, err error) {
	result = &v1alpha1.ChubaoMonitor{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("chubaomonitors").
		Body(chubaoMonitor).
		Do().
		Into(result)
	return
}

// Update takes the representation of a chubaoMonitor and updates it. Returns the server's representation of the chubaoMonitor, and an error, if there is any.
func (c *chubaoMonitors) Update(chubaoMonitor *v1alpha1.ChubaoMonitor) (result *v1alpha1.ChubaoMonitor, err error) {
	result = &v1alpha1.ChubaoMonitor{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("chubaomonitors").
		Name(chubaoMonitor.Name).
		Body(chubaoMonitor).
		Do().
		Into(result)
	return
}

// Delete takes name of the chubaoMonitor and deletes it. Returns an error if one occurs.
func (c *chubaoMonitors) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("chubaomonitors").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *chubaoMonitors) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("chubaomonitors").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched chubaoMonitor.
func (c *chubaoMonitors) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ChubaoMonitor, err error) {
	result = &v1alpha1.ChubaoMonitor{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("chubaomonitors").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
