/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/rook/rook/pkg/apis/chubao.rook.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeChubaoMonitors implements ChubaoMonitorInterface
type FakeChubaoMonitors struct {
	Fake *FakeChubaoV1alpha1
	ns   string
}

var chubaomonitorsResource = schema.GroupVersionResource{Group: "chubao.rook.io", Version: "v1alpha1", Resource: "chubaomonitors"}

var chubaomonitorsKind = schema.GroupVersionKind{Group: "chubao.rook.io", Version: "v1alpha1", Kind: "ChubaoMonitor"}

// Get takes name of the chubaoMonitor, and returns the corresponding chubaoMonitor object, and an error if there is any.
func (c *FakeChubaoMonitors) Get(name string, options v1.GetOptions) (result *v1alpha1.ChubaoMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(chubaomonitorsResource, c.ns, name), &v1alpha1.ChubaoMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChubaoMonitor), err
}

// List takes label and field selectors, and returns the list of ChubaoMonitors that match those selectors.
func (c *FakeChubaoMonitors) List(opts v1.ListOptions) (result *v1alpha1.ChubaoMonitorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(chubaomonitorsResource, chubaomonitorsKind, c.ns, opts), &v1alpha1.ChubaoMonitorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ChubaoMonitorList{ListMeta: obj.(*v1alpha1.ChubaoMonitorList).ListMeta}
	for _, item := range obj.(*v1alpha1.ChubaoMonitorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested chubaoMonitors.
func (c *FakeChubaoMonitors) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(chubaomonitorsResource, c.ns, opts))

}

// Create takes the representation of a chubaoMonitor and creates it.  Returns the server's representation of the chubaoMonitor, and an error, if there is any.
func (c *FakeChubaoMonitors) Create(chubaoMonitor *v1alpha1.ChubaoMonitor) (result *v1alpha1.ChubaoMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(chubaomonitorsResource, c.ns, chubaoMonitor), &v1alpha1.ChubaoMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChubaoMonitor), err
}

// Update takes the representation of a chubaoMonitor and updates it. Returns the server's representation of the chubaoMonitor, and an error, if there is any.
func (c *FakeChubaoMonitors) Update(chubaoMonitor *v1alpha1.ChubaoMonitor) (result *v1alpha1.ChubaoMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(chubaomonitorsResource, c.ns, chubaoMonitor), &v1alpha1.ChubaoMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChubaoMonitor), err
}

// Delete takes name of the chubaoMonitor and deletes it. Returns an error if one occurs.
func (c *FakeChubaoMonitors) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(chubaomonitorsResource, c.ns, name), &v1alpha1.ChubaoMonitor{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeChubaoMonitors) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(chubaomonitorsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ChubaoMonitorList{})
	return err
}

// Patch applies the patch and returns the patched chubaoMonitor.
func (c *FakeChubaoMonitors) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ChubaoMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(chubaomonitorsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ChubaoMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChubaoMonitor), err
}
