/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/rook/rook/pkg/apis/chubao.rook.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeChubaoObjectStores implements ChubaoObjectStoreInterface
type FakeChubaoObjectStores struct {
	Fake *FakeChubaoV1alpha1
	ns   string
}

var chubaoobjectstoresResource = schema.GroupVersionResource{Group: "chubao.rook.io", Version: "v1alpha1", Resource: "chubaoobjectstores"}

var chubaoobjectstoresKind = schema.GroupVersionKind{Group: "chubao.rook.io", Version: "v1alpha1", Kind: "ChubaoObjectStore"}

// Get takes name of the chubaoObjectStore, and returns the corresponding chubaoObjectStore object, and an error if there is any.
func (c *FakeChubaoObjectStores) Get(name string, options v1.GetOptions) (result *v1alpha1.ChubaoObjectStore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(chubaoobjectstoresResource, c.ns, name), &v1alpha1.ChubaoObjectStore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChubaoObjectStore), err
}

// List takes label and field selectors, and returns the list of ChubaoObjectStores that match those selectors.
func (c *FakeChubaoObjectStores) List(opts v1.ListOptions) (result *v1alpha1.ChubaoObjectStoreList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(chubaoobjectstoresResource, chubaoobjectstoresKind, c.ns, opts), &v1alpha1.ChubaoObjectStoreList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ChubaoObjectStoreList{ListMeta: obj.(*v1alpha1.ChubaoObjectStoreList).ListMeta}
	for _, item := range obj.(*v1alpha1.ChubaoObjectStoreList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested chubaoObjectStores.
func (c *FakeChubaoObjectStores) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(chubaoobjectstoresResource, c.ns, opts))

}

// Create takes the representation of a chubaoObjectStore and creates it.  Returns the server's representation of the chubaoObjectStore, and an error, if there is any.
func (c *FakeChubaoObjectStores) Create(chubaoObjectStore *v1alpha1.ChubaoObjectStore) (result *v1alpha1.ChubaoObjectStore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(chubaoobjectstoresResource, c.ns, chubaoObjectStore), &v1alpha1.ChubaoObjectStore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChubaoObjectStore), err
}

// Update takes the representation of a chubaoObjectStore and updates it. Returns the server's representation of the chubaoObjectStore, and an error, if there is any.
func (c *FakeChubaoObjectStores) Update(chubaoObjectStore *v1alpha1.ChubaoObjectStore) (result *v1alpha1.ChubaoObjectStore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(chubaoobjectstoresResource, c.ns, chubaoObjectStore), &v1alpha1.ChubaoObjectStore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChubaoObjectStore), err
}

// Delete takes name of the chubaoObjectStore and deletes it. Returns an error if one occurs.
func (c *FakeChubaoObjectStores) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(chubaoobjectstoresResource, c.ns, name), &v1alpha1.ChubaoObjectStore{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeChubaoObjectStores) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(chubaoobjectstoresResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ChubaoObjectStoreList{})
	return err
}

// Patch applies the patch and returns the patched chubaoObjectStore.
func (c *FakeChubaoObjectStores) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ChubaoObjectStore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(chubaoobjectstoresResource, c.ns, name, pt, data, subresources...), &v1alpha1.ChubaoObjectStore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChubaoObjectStore), err
}
