---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-user-account
  namespace: rook-chubao
stringData:
  username: "admin"
  password: "123456"
---
apiVersion: chubao.rook.io/v1alpha1
kind: ChubaoMonitor
metadata:
  name: mymonitor
  namespace: rook-chubao
spec:
  #    placement:
  #      nodeAffinity:
  #        requiredDuringSchedulingIgnoredDuringExecution:
  #          nodeSelectorTerms:
  #            - matchExpressions:
  #                - key: "rook-chubao-master"
  #                  operator: In
  #                  values:
  #                    - enabled
  prometheus:
    image: prom/prometheus:v2.13.1
    imagePullPolicy: IfNotPresent
    #    imagePullSecrets: ""
    consulUrl: http://consul-service.rook-chubao.svc.cluster.local:8500
    hostPath:
      Path: /var/lib/chubaofs_prometheus
  grafana:
    image: grafana/grafana:6.4.4
    imagePullPolicy: IfNotPresent
  #    imagePullSecrets: ""
  #    resources:
  #      limits:
  #        cpu: "500m"
  #        memory: "1024Mi"
  #      requests:
  #        cpu: "500m"
  #        memory: "1024Mi"
  console:
    image: chubaofs/cfs-server:0.0.1
    imagePullPolicy: IfNotPresent
    #    imagePullSecrets: ""
    masterAddr: "master-service.rook-chubao.svc.cluster.local:17110"
  #    replicas: 3
  #    clusterName: "mycluster"
  #    objectNodeDomain: "console.chubaofs.com"
  #    logLevel: "error"
  #    port: 17610
  #    resources:
  #      limits:
  #        cpu: "500m"
  #        memory: "1024Mi"
  #      requests:
  #        cpu: "500m"
  #        memory: "1024Mi"
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: chubao-monitor-ingress
  namespace: rook-chubao
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: monitor.chubaofs.com
      http:
        paths:
          - backend:
              serviceName: grafana-service
              servicePort: 3000
    - host: console.chubaofs.com
      http:
        paths:
          - backend:
              serviceName: console-service
              servicePort: 17610
---
