---
apiVersion: v1
kind: Pod
metadata:
  name: rook-cfs-demo-pod
  namespace: rook-chubao
spec:
  containers:
    - name: web-server
      image: nginx
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www/html
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: rook-cfs-pvc-demo
